### PR TITLE
Allow process env for port number and have default 4000

### PR DESCRIPTION
**Pull request by sulthan-ahmed**

### CODE REVIEW

**Review by chrisns — APPROVED** [review]
not sure why you need a config.js but whatever

**Review by danielepolencic — CHANGES_REQUESTED** [review]
Did you run a linter?

**Comment by sulthan-ahmed** [comment]
@danielepolencic The linter is on the other PR, https://github.com/UKHomeOffice/mapping-participants/pull/3/commits

Is there a particular issue?

**Comment by sulthan-ahmed** [comment]
@danielepolencic I've linted the issues, thanks for highlighting, is this now ok for you to approve?

**Review by danielepolencic — APPROVED** [review]

**Comment by sulthan-ahmed** [comment]
Thanks @danielepolencic

**Pull request merged**
